#### Bathroom light brightness
- alias: Dim bathroom lights when its late
  hide_entity: True
  trigger:
    - platform: state
      entity_id: light.bathroom
      to: 'on'
  condition:
    condition: time
    after: '20:00:00'
    before: '07:30:00'
  action:
    service: scene.turn_on
    entity_id: scene.bathroom_dim

- alias: Put bathroom lights on full in the day
  hide_entity: True
  trigger:
    - platform: state
      entity_id: light.bathroom
      to: 'on'
  condition:
    condition: time
    after: '07:30:00'
    before: '20:00:00'
  action:
    service: scene.turn_on
    entity_id: scene.bathroom_normal

- alias: Turn on hall light when the front door opens
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door
      to: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: light.hall

- alias: Turn on conservatory light when the back door opens
  trigger:
    - platform: state
      entity_id: binary_sensor.conservatory
      to: 'on'
  condition:
    condition: state
    entity_id: sun.sun
    state: 'below_horizon'
  action:
    service: homeassistant.turn_on
    entity_id: switch.conservatory

### Fake the lights

#- alias: Lights on like we are home
#  trigger:
#    - platform: time
#      at: '19:30:00'
#  action:
#    - service: light.turn_on
#      entity_id: light.living_room

#- alias: Lights off like we are home
#  trigger:
#    - platform: time
#      at: '22:01:00'
#  action:
#    - service: light.turn_off
#      entity_id: light.living_room

#- alias: kitchen on like we are home
#  trigger:
#    - platform: time
#      at: '21:45:00'
#  action:
#    - service: light.turn_on
#      entity_id: light.kitchen

#- alias: kitchen off like we are home
#  trigger:
#    - platform: time
#      at: '22:00:00'
#  action:
#    - service: light.turn_off
#      entity_id: light.kitchen

#- alias: bathroom on like we are home
#  trigger:
#    - platform: time
#      at: '22:00:00'
#  action:
#    - service: light.turn_on
#      entity_id: light.bathroom

#- alias: bathroom off like we are home
#  trigger:
#    - platform: time
#      at: '22:07:00'
#  action:
#    - service: light.turn_off
#      entity_id: light.bathroom

#- alias: bedroom on like we are home
#  trigger:
#    - platform: time
#      at: '22:02:00'
#  action:
#    - service: switch.turn_on
#      entity_id: switch.hannahs_lamp

#- alias: bedroom off like we are home
#  trigger:
#    - platform: time
#      at: '22:10:00'
#  action:
#    - service: switch.turn_off
#      entity_id: switch.hannahs_lamp

#### People Status
- alias: Mark person as just arrived
  hide_entity: True
  trigger:
    - platform: state
      entity_id: device_tracker.tom_gs6
      from: 'not_home'
      to: 'home'
    - platform: state
      entity_id: device_tracker.hannah_gs7
      from: 'not_home'
      to: 'home'
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'device_tracker.tom_gs6' %}
            input_select.tom_status_dropdown
          {% else %}
            input_select.hannah_status_dropdown
          {% endif %}
        option: Just Arrived
 
- alias: Mark person as home
  hide_entity: True
  trigger:
    - platform: state
      entity_id: input_select.tom_status_dropdown
      to: 'Just Arrived'
      for:
        minutes: 10
    - platform: state
      entity_id: input_select.hannah_status_dropdown
      to: 'Just Arrived'
      for:
        minutes: 10
    - platform: state
      entity_id: input_select.tom_status_dropdown
      from: 'Just Left'
      to: 'Just Arrived'
    - platform: state
      entity_id: input_select.hannah_status_dropdown
      from: 'Just Left'
      to: 'Just Arrived'
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'input_select.tom_status_dropdown' %}
            input_select.tom_status_dropdown
          {% else %}
            input_select.hannah_status_dropdown
          {% endif %}
        option: Home
 
- alias: Mark person as just left
  hide_entity: True
  trigger:
    - platform: state
      entity_id: device_tracker.tom_gs6
      from: 'home'
      to: 'not_home'
    - platform: state
      entity_id: device_tracker.hannah_gs7
      from: 'home'
      to: 'not_home'
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'device_tracker.tom_gs6' %}
            input_select.tom_status_dropdown
          {% else %}
            input_select.hannah_status_dropdown
          {% endif %}
        option: Just Left
 
- alias: Mark person as away
  hide_entity: True
  trigger:
    - platform: state
      entity_id: input_select.tom_status_dropdown
      to: 'Just Left'
      for:
        minutes: 10
    - platform: state
      entity_id: input_select.hannah_status_dropdown
      to: 'Just Left'
      for:
        minutes: 10
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'input_select.tom_status_dropdown' %}
            input_select.tom_status_dropdown
          {% else %}
            input_select.hannah_status_dropdown
          {% endif %}
        option: Away
 
- alias: Mark person as extended away
  hide_entity: True
  trigger:
    - platform: state
      entity_id: input_select.tom_status_dropdown
      to: 'Away'
      for:
        hours: 24
    - platform: state
      entity_id: input_select.hannah_status_dropdown
      to: 'Away'
      for:
        hours: 24
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'input_select.tom_status_dropdown' %}
            input_select.tom_status_dropdown
          {% else %}
            input_select.hannah_status_dropdown
          {% endif %}
        option: Extended Away

#- alias: Front Door Opened
#  hide_entity: True
#  trigger:
#    - platform: state
#      entity_id: sensor.front_door
#      from: 'CLOSED'
#      to: 'OPEN'
#    - platform: state
#      entity_id: group.family
#      to: 'not_home'
#  action:
#    - service: notify.tom
#      data:
#        message: "Front Door Opened"
