#### Bathroom light brightness so we don't disturb the kids when its late

- alias: Dim bathroom lights when its late
  trigger:
    - platform: state
      entity_id: light.bathroom
      to: 'on'
  condition:
    condition: time
    after: '20:00:00'
    before: '07:30:00'
  action:
    service: scene.turn_on
    entity_id: scene.bathroom_dim

- alias: Put bathroom lights on full in the day
  trigger:
    - platform: state
      entity_id: light.bathroom
      to: 'on'
  condition:
    condition: time
    after: '07:30:00'
    before: '20:00:00'
  action:
    service: scene.turn_on
    entity_id: scene.bathroom_normal