#### Bathroom light brightness so we don't disturb the kids when its late

- alias: Good Night Trigger
  trigger:
    - platform: state
      entity_id: input_boolean.goodnight
      to: 'on'
      from: 'off'

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'

  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.goodnight
    - service: tts.google_say
      data:
        entity_id:
          - media_player.kitchen_home
          - media_player.living_room_home
        message: "Night night, sleep tight, Don't let the bedbugs bite."
    - service: script.goodnight