
- alias: Set Goggle Home Volume
  trigger:
    - platform: state
      entity_id: input_number.google_home
  condition:
    - condition: template
      value_template: "{{ not is_state_attr('media_player.kitchen_home', 'volume_level', states('input_number.google_home') | int / 100) }}"
  action:
    - service: media_player.volume_set
      entity_id:
        - media_player.kitchen_home
        - media_player.living_room_home
      data_template:
        volume_level: "{{ states('input_number.google_home') | int / 100 }}"